# Generated by Django 2.1.2 on 2018-11-05 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refImb', models.CharField(max_length=50, null=True)),
                ('date_effective_de_raccordement', models.DateTimeField(null=True, verbose_name='dare effective de raccordement')),
            ],
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(null=True, verbose_name='date published')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportOptimum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier', models.CharField(max_length=50, null=True)),
                ('code_regroupement_syndic', models.CharField(max_length=50, null=True)),
                ('id_pm', models.CharField(max_length=50, null=True)),
                ('type_de_pm', models.CharField(max_length=50, null=True)),
                ('etat_de_pm', models.CharField(max_length=50, null=True)),
                ('date_etat_pm', models.DateTimeField(null=True, verbose_name='Date Etat PM')),
                ('date_construction_pm', models.DateTimeField(null=True, verbose_name='Date Constrution PM')),
                ('id_pa', models.CharField(max_length=50, null=True)),
                ('etat_de_pa', models.CharField(max_length=50, null=True)),
                ('identifiant_processus', models.CharField(max_length=50, null=True)),
                ('date_maj_contour', models.DateTimeField(null=True, verbose_name='Date Maj contour')),
                ('num_voie', models.IntegerField(null=True)),
                ('num_cplt', models.IntegerField(null=True)),
                ('voie', models.CharField(max_length=50, null=True)),
                ('adresse', models.CharField(max_length=50, null=True)),
                ('batiment', models.CharField(max_length=50, null=True)),
                ('cp', models.CharField(max_length=50, null=True)),
                ('Localite', models.CharField(max_length=50, null=True)),
                ('rivoli', models.CharField(max_length=50, null=True)),
                ('operateur_d_imeuble', models.CharField(max_length=50, null=True)),
                ('etat_negociation', models.CharField(max_length=50, null=True)),
                ('etat_technique', models.CharField(max_length=50, null=True)),
                ('etat_site', models.CharField(max_length=50, null=True)),
                ('site_bloque', models.CharField(max_length=50, null=True)),
                ('type_site', models.CharField(max_length=50, null=True)),
                ('detection_zlin', models.CharField(max_length=50, null=True)),
                ('pre_equipe', models.CharField(max_length=50, null=True)),
                ('nb_logement', models.IntegerField(null=True)),
                ('nb_logement_r', models.IntegerField(null=True)),
                ('nb_logement_p', models.IntegerField(null=True)),
                ('typologie', models.CharField(max_length=50, null=True)),
                ('civilite_pdt_conseil_syndical', models.CharField(max_length=50, null=True)),
                ('nom_pdt_conseil_syndical', models.CharField(max_length=50, null=True)),
                ('prenom_pdt_conseil_syndical', models.CharField(max_length=50, null=True)),
                ('num_tel_pdt_conseil_syndical', models.CharField(max_length=50, null=True)),
                ('num_mobile_pdt_conseil_syndical', models.CharField(max_length=50, null=True)),
                ('fax_pdt_conseil_syndical', models.CharField(max_length=50, null=True)),
                ('email_pdt_conseil_syndical', models.CharField(max_length=50, null=True)),
                ('nra', models.CharField(max_length=50, null=True)),
                ('type_blocage_site', models.CharField(max_length=50, null=True)),
                ('cause_blocage_syndic', models.CharField(max_length=50, null=True)),
                ('etat_pre_etude_site', models.CharField(max_length=50, null=True)),
                ('etat_reseau_t_d', models.CharField(max_length=50, null=True)),
                ('etude_site', models.CharField(max_length=50, null=True)),
                ('etat_etude_site', models.CharField(max_length=50, null=True)),
                ('date_fin_etude_site', models.DateTimeField(null=True, verbose_name='date fin étude site')),
                ('resultat_etude_site', models.CharField(max_length=50, null=True)),
                ('date_theorique_raccordement', models.DateTimeField(null=True, verbose_name='Date théorique raccordement')),
                ('date_raccordement_au_pm_ou_au_pa', models.DateTimeField(null=True, verbose_name='Date raccordement au PM ou au PA')),
                ('identifiant_pb', models.CharField(max_length=50, null=True)),
                ('date_pose_du_pb', models.DateTimeField(null=True, verbose_name='Date pose du PB')),
                ('date_effective_raccordement', models.DateTimeField(null=True, verbose_name='Date effective raccordement')),
                ('presence_dta', models.CharField(max_length=50, null=True)),
                ('nom_contact_syndic', models.CharField(max_length=50, null=True)),
                ('prenom_contact_syndic', models.CharField(max_length=50, null=True)),
                ('num_tel_contact_syndic', models.CharField(max_length=50, null=True)),
                ('date_affectation_negociateur', models.DateTimeField(null=True, verbose_name='Date affectation négociateur')),
                ('negociateur_interne', models.CharField(max_length=50, null=True)),
                ('negociateur_externe', models.CharField(max_length=50, null=True)),
                ('premier_conctact', models.CharField(max_length=50, null=True)),
                ('date_rdv_syndic', models.DateTimeField(null=True, verbose_name='Date RDV Syndic')),
                ('attente', models.CharField(max_length=50, null=True)),
                ('date_ag', models.DateTimeField(null=True, verbose_name='Date AG')),
                ('ag_non_pertinente', models.CharField(max_length=50, null=True)),
                ('envoi_accord_syndic', models.CharField(max_length=50, null=True)),
                ('date_retour_convention', models.DateTimeField(null=True, verbose_name='Date Retour Convention')),
                ('attente_probation', models.CharField(max_length=50, null=True)),
                ('retour_accord_syndic', models.CharField(max_length=50, null=True)),
                ('refus_accord_syndic', models.CharField(max_length=50, null=True)),
                ('date_mesc_arcep_pm', models.DateTimeField(null=True, verbose_name='Date MESC ARCEP PM')),
                ('date_pose_pre', models.DateTimeField(null=True, verbose_name='Date Pose PRE')),
                ('import_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imports.Import')),
            ],
        ),
        migrations.CreateModel(
            name='Pa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refPa', models.CharField(max_length=50, null=True)),
                ('import_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imports.Import')),
            ],
        ),
        migrations.CreateModel(
            name='Pmz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refPmz', models.CharField(max_length=50, null=True)),
                ('import_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imports.Import')),
            ],
        ),
        migrations.CreateModel(
            name='RefImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pa',
            name='pmz_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imports.Pmz'),
        ),
        migrations.AddField(
            model_name='import',
            name='ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imports.RefImport'),
        ),
        migrations.AddField(
            model_name='imb',
            name='import_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imports.Import'),
        ),
        migrations.AddField(
            model_name='imb',
            name='pa_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imports.Pa'),
        ),
    ]
