# Generated by Django 2.1.2 on 2018-10-12 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imb',
            fields=[
                ('idImb', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_effective_de_raccordement', models.DateTimeField(verbose_name='dare effective de raccordement')),
                ('importe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imports.ImportOptimum')),
            ],
        ),
        migrations.CreateModel(
            name='Pa',
            fields=[
                ('idPa', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('importe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imports.ImportOptimum')),
            ],
        ),
        migrations.AddField(
            model_name='imb',
            name='paParent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imports.Pa'),
        ),
    ]
