# Generated by Django 2.1.2 on 2018-10-31 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refImb', models.CharField(max_length=50, null=True)),
                ('date_effective_de_raccordement', models.DateTimeField(null=True, verbose_name='dare effective de raccordement')),
            ],
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(null=True, verbose_name='date published')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refPa', models.CharField(max_length=50, null=True)),
                ('import_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imports.Import')),
            ],
        ),
        migrations.CreateModel(
            name='RefImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='importoptimum',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='Localite',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='adresse',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='ag_non_pertinente',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='attente',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='attente_probation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='batiment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='cause_blocage_syndic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='civilite_pdt_conseil_syndical',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='code_regroupement_syndic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='cp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_affectation_negociateur',
            field=models.DateTimeField(null=True, verbose_name='Date affectation négociateur'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_ag',
            field=models.DateTimeField(null=True, verbose_name='Date AG'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_construction_pm',
            field=models.DateTimeField(null=True, verbose_name='Date Constrution PM'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_effective_raccordement',
            field=models.DateTimeField(null=True, verbose_name='Date effective raccordement'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_etat_pm',
            field=models.DateTimeField(null=True, verbose_name='Date Etat PM'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_fin_etude_site',
            field=models.DateTimeField(null=True, verbose_name='date fin étude site'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_maj_contour',
            field=models.DateTimeField(null=True, verbose_name='Date Maj contour'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_mesc_arcep_pm',
            field=models.DateTimeField(null=True, verbose_name='Date MESC ARCEP PM'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_pose_du_pb',
            field=models.DateTimeField(null=True, verbose_name='Date pose du PB'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_pose_pre',
            field=models.DateTimeField(null=True, verbose_name='Date Pose PRE'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_raccordement_au_pm_ou_au_pa',
            field=models.DateTimeField(null=True, verbose_name='Date raccordement au PM ou au PA'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_rdv_syndic',
            field=models.DateTimeField(null=True, verbose_name='Date RDV Syndic'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_retour_convention',
            field=models.DateTimeField(null=True, verbose_name='Date Retour Convention'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_theorique_raccordement',
            field=models.DateTimeField(null=True, verbose_name='Date théorique raccordement'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='detection_zlin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='dossier',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='email_pdt_conseil_syndical',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='envoi_accord_syndic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='etat_de_pa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='etat_de_pm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='etat_etude_site',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='etat_negociation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='etat_pre_etude_site',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='etat_reseau_t_d',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='etat_site',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='etat_technique',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='etude_site',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='fax_pdt_conseil_syndical',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='id_pa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='id_pm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='identifiant_pb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='identifiant_processus',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='nb_logement',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='nb_logement_p',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='nb_logement_r',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='negociateur_externe',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='negociateur_interne',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='nom_contact_syndic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='nom_pdt_conseil_syndical',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='nra',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='num_cplt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='num_mobile_pdt_conseil_syndical',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='num_tel_contact_syndic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='num_tel_pdt_conseil_syndical',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='num_voie',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='operateur_d_imeuble',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='pre_equipe',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='premier_conctact',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='prenom_contact_syndic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='prenom_pdt_conseil_syndical',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='presence_dta',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='refus_accord_syndic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='resultat_etude_site',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='retour_accord_syndic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='rivoli',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='site_bloque',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='type_blocage_site',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='type_de_pm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='type_site',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='typologie',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='voie',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='import',
            name='ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imports.RefImport'),
        ),
        migrations.AddField(
            model_name='imb',
            name='import_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imports.Import'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='import_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imports.Import'),
        ),
    ]
