# Generated by Django 2.1.2 on 2018-10-16 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imports', '0002_auto_20181012_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='importoptimum',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pa',
            name='importe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imports.ImportOptimum'),
        ),
    ]
