# Generated by Django 2.1.2 on 2018-10-16 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_auto_20181016_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importoptimum',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pa',
            name='importe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imports.ImportOptimum'),
        ),
    ]
