# Generated by Django 2.1.2 on 2018-10-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_auto_20181016_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imb',
            name='importe',
        ),
        migrations.RemoveField(
            model_name='imb',
            name='paParent',
        ),
        migrations.RemoveField(
            model_name='importoptimum',
            name='author',
        ),
        migrations.RemoveField(
            model_name='importoptimum',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='pa',
            name='importe',
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='charges_etude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_fin_distribution',
            field=models.DateTimeField(null=True, verbose_name='date fin distribution'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_fin_transport',
            field=models.DateTimeField(null=True, verbose_name='date fin transport'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_lancement_t_d',
            field=models.DateTimeField(null=True, verbose_name='date lancement T/D'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_mise_a_disposition_pre_etude',
            field=models.DateTimeField(null=True, verbose_name='date mise à disposition pré-étude'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='etat_reseau_t_d',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='pez',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='realisation_reseau_t_d',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='reseau_impossible',
            field=models.BooleanField(null=True),
        ),
    ]
