# Generated by Django 2.1.2 on 2018-10-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0005_auto_20181017_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='importoptimum',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
