# Generated by Django 2.1.2 on 2018-10-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0006_importoptimum_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importoptimum',
            name='date_fin_distribution',
        ),
        migrations.RemoveField(
            model_name='importoptimum',
            name='date_fin_transport',
        ),
        migrations.RemoveField(
            model_name='importoptimum',
            name='date_lancement_t_d',
        ),
        migrations.RemoveField(
            model_name='importoptimum',
            name='date_mise_a_disposition_pre_etude',
        ),
        migrations.RemoveField(
            model_name='importoptimum',
            name='etat_reseau_t_d',
        ),
        migrations.RemoveField(
            model_name='importoptimum',
            name='realisation_reseau_t_d',
        ),
        migrations.RemoveField(
            model_name='importoptimum',
            name='reseau_impossible',
        ),
    ]
