# Generated by Django 2.1.2 on 2018-10-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0007_auto_20181019_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='importoptimum',
            name='Localite',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='adresse',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='adresse_provisoire',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='ag_non_pertinente',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='annee_programme',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='attente',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='attente_probation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='batiment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='cause_blocage_syndic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='charge_etude_arbre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='civilite_pdt_conseil_syndical',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='cle_du_site_calculee',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='cle_du_site_reelle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='code_iris',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='code_regroupement_syndic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='code_syndic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='code_taille_site',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='cp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_affectation_negociateur',
            field=models.DateTimeField(null=True, verbose_name='Date affectation négociateur'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_ag',
            field=models.DateTimeField(null=True, verbose_name='Date AG'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_annulation_commande',
            field=models.DateTimeField(null=True, verbose_name='date dern. ISA'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_annulation_pre_etude_ui',
            field=models.DateTimeField(null=True, verbose_name='date annulation pré-étude (UI)'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_annulation_production',
            field=models.DateTimeField(null=True, verbose_name='date fin étude site'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_construction_pm',
            field=models.DateTimeField(null=True, verbose_name='Date Constrution PM'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_de_construction',
            field=models.DateTimeField(null=True, verbose_name='date de construction'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_de_saisie_de_l_accord_syndic',
            field=models.DateTimeField(null=True, verbose_name='Date validation pré-étude par syndic'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_debut_raccordement',
            field=models.DateTimeField(null=True, verbose_name='date début raccordement'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_demande_de_modification_de_pre_etude',
            field=models.DateTimeField(null=True, verbose_name='date demande de modification de pré-étude'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_denonciation_syndic',
            field=models.DateTimeField(null=True, verbose_name='Date dénonciation syndic'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_depl_imm',
            field=models.DateTimeField(null=True, verbose_name='date depl. Imm'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_depl_pav',
            field=models.DateTimeField(null=True, verbose_name='date depl. Pav'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_dern_isa',
            field=models.DateTimeField(null=True, verbose_name='date dern. ISA'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_dernier_envoi_pre_etude_syndic',
            field=models.DateTimeField(null=True, verbose_name='Date dernier envoi syndic pré-étude'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_effective_raccordement',
            field=models.DateTimeField(null=True, verbose_name='Date effective raccordement'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_envoi_pre_etude_syndic',
            field=models.DateTimeField(null=True, verbose_name='Date envoi pré-étude au syndic'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_etat_pm',
            field=models.DateTimeField(null=True, verbose_name='Date Etat PM'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_fin_distribution',
            field=models.DateTimeField(null=True, verbose_name='date fin distribution'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_fin_etude_site',
            field=models.DateTimeField(null=True, verbose_name='date fin étude site'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_fin_etude_zone_arriere_du_pa',
            field=models.DateTimeField(null=True, verbose_name='Date Fin Etude Zone Arrière du PA '),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_fin_transport',
            field=models.DateTimeField(null=True, verbose_name='date fin transport'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_lancement_pre_etude',
            field=models.DateTimeField(null=True, verbose_name='date lancement pré-étude'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_lancement_t_d',
            field=models.DateTimeField(null=True, verbose_name='date lancement T/D'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_maj_contour',
            field=models.DateTimeField(null=True, verbose_name='Date Maj contour'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_mesc_arcep_pm',
            field=models.DateTimeField(null=True, verbose_name='Date MESC ARCEP PM'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_mesc_arcep_site',
            field=models.DateTimeField(null=True, verbose_name='Date MESC ARCEP Site'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_mesc_ft',
            field=models.DateTimeField(null=True, verbose_name='Date MESC FT'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_mise_a_disposition_pre_etude',
            field=models.DateTimeField(null=True, verbose_name='date mise à disposition pré-étude'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_pose_du_pb',
            field=models.DateTimeField(null=True, verbose_name='Date pose du PB'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_pose_pre',
            field=models.DateTimeField(null=True, verbose_name='Date Pose PRE'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_programmee_raccordement',
            field=models.DateTimeField(null=True, verbose_name='Date programmée raccordement'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_raccordement_au_pm_ou_au_pa',
            field=models.DateTimeField(null=True, verbose_name='Date raccordement au PM ou au PA'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_rdv_syndic',
            field=models.DateTimeField(null=True, verbose_name='Date RDV Syndic'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_recept_bon_pre_etude',
            field=models.DateTimeField(null=True, verbose_name='Date récept. bon pré-étude'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_retour_convention',
            field=models.DateTimeField(null=True, verbose_name='Date Retour Convention'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_souhaitee_pre_etude',
            field=models.DateTimeField(null=True, verbose_name='Date souhaitée pré-étude'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_theorique_deblocage_syndic',
            field=models.DateTimeField(null=True, verbose_name='date deblocage syndic'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_theorique_raccordement',
            field=models.DateTimeField(null=True, verbose_name='Date théorique raccordement'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='date_validation_pre_etude_par_syndic',
            field=models.DateTimeField(null=True, verbose_name='Date validation pré-étude par syndic'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='densité_iris',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='dernier_dem_pap',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='derniere_relance_syndic',
            field=models.DateTimeField(null=True, verbose_name='Dern. Relance syndic'),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='detection_zlin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='dlpi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='domaine',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='dossier',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='dr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='email_conseil_syndical',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='ensemble_immobilier',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='envoi_accord_syndic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='envoi_commande_acces_immeuble',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='escalier',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='etat_acces_immeuble',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='etat_commande_producction',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='etat_de_deploiement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='etat_de_pa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='etat_de_pm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='etat_etude_site',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='etat_negociation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='etat_pre_etude_site',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='etat_reseau_t_d',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='etat_site',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='etat_technique',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='etat_zlin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='etude_site',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='fax_pdt_conseil_syndical',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='fttdp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='id_pa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='id_pm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='identifiant_pb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='identifiant_processus',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='immeuble_prioritaire',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='interlocuteur_unique',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='j3m',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='marquage_temporaire_upr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='motif_denonciation_syndic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='motif_refus',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='nb_demarchage_pap',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='nb_escaliers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='nb_etages',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='nb_logement',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='nb_logement_de_regroupement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='nb_logement_p',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='nb_logement_r',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='nb_pre_commandes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='nb_pre_signes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='nb_prise_interet',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='negociateur_externe',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='negociateur_interne',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='nom_contact_syndic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='nom_pdt_conseil_syndical',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='nom_syndic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='nra',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='num_asoeie',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='num_cplt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='num_de_lot',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='num_mobile_pdt_conseil_syndical',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='num_tel_contact_syndic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='num_tel_pdt_conseil_syndical',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='num_voie',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='operateur_d_imeuble',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='p_a_p',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='pa_ready',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='permis_de_construire',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='phase_depl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='potentiel_immeuble',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='pre_equipe',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='premier_conctact',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='premier_dem_pap',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='prenom_contact_syndic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='prenom_pdt_conseil_syndical',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='presence_concurrent',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='presence_dta',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='presence_vip',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='qualite_base_descriptive',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='qualite_etude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='realisation_reseau_t_d',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='ref_arbre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='refus_attente_syndic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='reseau_impossible',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='resulte_etude_site',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='retour_attente_syndic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='retour_syndic_pre_etude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='rivoli',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='seuil_prospects',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='site_bloque',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='site_hebergeant_le_pmi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='site_sature',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='suivi_strategique_upr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='suivi_syndic_particulier',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='taille_site',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='type_blocage_site',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='type_de_commercialisation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='type_de_pm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='type_processus_particulier',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='type_site',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='typologie',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='validation_commande_acces_immeuble',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='verification_technique',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='voie',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='zone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='zone_arcep_pm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='zone_arcep_site',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='zone_nouvelle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importoptimum',
            name='zone_rome',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
